- hosts: all
  become: yes
  vars_files:
    - defaults/main.yml
    - defaults/local.yml
  roles:
    # No methods to run some of the roles. I circumvent this by using tags
    # `ansible-playbook site.yml`: install all packages
    # `ansible-playbook site.yml --tags python`: install python
    - { role: apt, tags: [apt] }
    - { role: common, tags: [common] }
    - { role: iptables, tags: [iptables] }
    - { role: nginx, tags: [nginx] }
    - { role: neovim, tags: [neovim] }
    - { role: postfix, tags: [postfix] }
    - { role: python, tags: [python] }
    - { role: squid, tags: [squid] }
    - { role: shadowsocks, tags: [shadowsocks] }
    - { role: strongswan, tags: [strongswan] }
    - { role: tinc, tags: [tinc] }
    - { role: unbound, tags: [unbound] }
    #- { role: nodejs, tags: [nodejs] }
    #- { role: postgresql, tags: [postgresql] }
    #- { role: elasticsearch, tags: [elasticsearch] }
    # grafana & influxdb
    #- { role: grafana, tags: [grafana] }
