- name: Add nodesource.com repository
  apt_repository: repo='deb https://deb.nodesource.com/node_{{latest.nodejs}} {{ansible_distribution_release}} main'
- name: Install Node.js
  apt: name=nodejs state=latest

- name: Install PhantomJS
  apt: name=phantomjs
